### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dominikpanzer**
fixed link formatting for abapDI

### CODE REVIEW

**Comment by Ennowulff** [comment]
@HuprichT would you like to try to review again? I updated the settings which IMHO were responsible. thanks

**Comment by HuprichT** [comment]
@Ennowulff looks good, no reviews possible anymore :)

**Comment by Ennowulff** [comment]
Thanks for verifying, @HuprichT ! 👍

**Comment by dominikpanzer** [comment]
pst. the PR was actually a useful update, maybe merging it is a good idea ;-)

**Pull request merged**
